APPINT-32811: CVE for commons-codec-1.6 on studio 7.3
Talend/tesb-studio-se pull request #1139
Opened 2021-04-16 14:05 UTC by vdrokov

2021-04-16 14:22 UTC, apoltavtsev approved these changes
OK

2021-04-18 04:09 UTC, xldai requested changes

2021-04-18 04:09 UTC, xldai commented on main/plugins/org.talend.designer.esb.components.ws.consumer/plugin.xml
>              uripath="platform:/base/plugins/org.apache.commons.codec_1.6.0.v201305230611.jar"
org.apache.commons.codec_1.6.0.v201305230611.jar still?

2021-04-18 12:42 UTC, xldai requested changes

2021-04-18 12:42 UTC, xldai commented on main/plugins/org.talend.designer.camel.components.localprovider/components/cMessagingEndpoint/cMessagingEndpoint_java.xml
> +            <IMPORT MODULE="commons-codec-1.15" MVN="mvn:commons-codec/commons-codec/1.6" REQUIRED="true" />
MVN url still 1.6

2021-04-18 17:18 UTC, apoltavtsev approved these changes
LGTM

2021-04-19 03:18 UTC, csuntalendbj approved these changes
LGTM

2021-04-19 03:21 UTC, xldai approved these changes
Corrected the fixes.

2021-04-19 03:21 UTC, merged