Bkatiukhov fix appint 32851 73m
Talend/tesb-studio-se pull request #1165
Opened 2021-05-11 09:03 UTC by bkatiukhov

2021-05-13 03:39 UTC, xldai requested changes

2021-05-13 03:39 UTC, xldai commented on main/plugins/org.talend.designer.camel.components.localprovider/pom.xml
> +        <jackson.version>2.10.1</jackson.version>
this is wrong jackson version.
should remove this line, and reuse the one from the root pom
<jackson.version>2.11.4</jackson.version>

2021-05-13 03:45 UTC, xldai commented
Pushed one fix commit.

2021-05-13 03:46 UTC, xldai approved these changes
LGTM

2021-06-02 07:41 UTC, csuntalendbj approved these changes
LGTM

2021-06-07 10:34 UTC, merged