Jill/fix/master/appint 32549
Talend/tesb-studio-se pull request #1532
Opened 2022-03-08 04:58 UTC by jillyan

2022-03-28 02:30 UTC, xldai commented
Better add a description of the changes in the ESB_DEMOS.zip.
is it still necessary to update the ESB_DEMOS.zip after provided RemoveSlashServicesInEndpointMigrationTask?

2022-03-28 02:30 UTC, xldai requested changes

2022-03-28 02:30 UTC, xldai commented on main/plugins/org.talend.camel.designer/src/main/java/org/talend/camel/designer/migration/RemoveSlashServicesInEndpointMigrationTask.java
> +            } catch (PersistenceException e) {
Here forgot adding a generateReportRecord() to generate migration report.

2022-03-28 02:30 UTC, xldai commented on main/plugins/org.talend.camel.designer/src/main/java/org/talend/camel/designer/migration/RemoveSlashServicesInEndpointMigrationTask.java
> +                if (nodeNameEndpointNameMap.keySet().contains(componentName)) {
Here should check ONLY in case of the cSOAP or cREST components as a provider (the first component in the route flow)

2022-03-28 07:02 UTC, jillyan commented on main/plugins/org.talend.camel.designer/src/main/java/org/talend/camel/designer/migration/RemoveSlashServicesInEndpointMigrationTask.java
> +                if (nodeNameEndpointNameMap.keySet().contains(componentName)) {
Actually, cSOAP and cREST could be the end node sometimes, as example in RESTtoSOAP and SOAPtoREST.
And this migration will also check endpoint for cSOAP and cREST as client.

2022-03-28 09:33 UTC, xldai approved these changes
LGTM

2022-03-30 01:55 UTC, hweitalend approved these changes
LGTM

2022-03-30 01:57 UTC, merged